# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squashapp', '0004_auto_20150713_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreviewdetails',
            name='bpw_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='dba_report_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='dba_report_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='dba_report_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='dba_report_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='diff_report_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='diff_report_dev_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='draftrc_dev_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='exec_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='exec_dev_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='exec_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='executables_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='finalrc_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='fs_panel_review_applicable',
            field=models.CharField(default=b'No', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='fs_panel_review_mom_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='help_files_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='help_files_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='itr2end_tagging_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='mpp_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='mpp_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='mpp_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='no_of_user_manuals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='order_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='oum_estimator_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='pkom_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='pkom_checklist_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='pkom_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='pmp_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='pmp_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='pmp_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='pmp_sme_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='project_plans_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='rc_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='release_note_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='release_note_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='release_note_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='release_note_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='scm_report_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='scm_report_dev_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='scm_report_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='stp_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='stp_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='stp_dev_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='stp_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='stp_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='um_baselined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='um_devteam_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='um_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='um_qmg_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='um_testteam_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreviewdetails',
            name='user_manuals_applicable',
            field=models.CharField(default=b'Yes', max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
    ]
